from __future__ import annotations



def forward(self, L_inputs_0_ : torch.Tensor):
    l_inputs_0_ = L_inputs_0_
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:159, code: x = self.layers(x)
    l__mod___layers_0 = self.L__mod___layers_0(l_inputs_0_);  l_inputs_0_ = None
    l__mod___layers_1 = self.L__mod___layers_1(l__mod___layers_0);  l__mod___layers_0 = None
    l__mod___layers_2 = self.L__mod___layers_2(l__mod___layers_1);  l__mod___layers_1 = None
    l__mod___layers_3 = self.L__mod___layers_3(l__mod___layers_2);  l__mod___layers_2 = None
    l__mod___layers_4 = self.L__mod___layers_4(l__mod___layers_3);  l__mod___layers_3 = None
    l__mod___layers_5 = self.L__mod___layers_5(l__mod___layers_4);  l__mod___layers_4 = None
    l__mod___layers_6 = self.L__mod___layers_6(l__mod___layers_5);  l__mod___layers_5 = None
    l__mod___layers_7 = self.L__mod___layers_7(l__mod___layers_6);  l__mod___layers_6 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:63, code: return self.layers(input)
    getattr_getattr_l__mod___layers___8_____0___layers_0 = self.getattr_getattr_L__mod___layers___8_____0___layers_0(l__mod___layers_7);  l__mod___layers_7 = None
    getattr_getattr_l__mod___layers___8_____0___layers_1 = self.getattr_getattr_L__mod___layers___8_____0___layers_1(getattr_getattr_l__mod___layers___8_____0___layers_0);  getattr_getattr_l__mod___layers___8_____0___layers_0 = None
    getattr_getattr_l__mod___layers___8_____0___layers_2 = self.getattr_getattr_L__mod___layers___8_____0___layers_2(getattr_getattr_l__mod___layers___8_____0___layers_1);  getattr_getattr_l__mod___layers___8_____0___layers_1 = None
    getattr_getattr_l__mod___layers___8_____0___layers_3 = self.getattr_getattr_L__mod___layers___8_____0___layers_3(getattr_getattr_l__mod___layers___8_____0___layers_2);  getattr_getattr_l__mod___layers___8_____0___layers_2 = None
    getattr_getattr_l__mod___layers___8_____0___layers_4 = self.getattr_getattr_L__mod___layers___8_____0___layers_4(getattr_getattr_l__mod___layers___8_____0___layers_3);  getattr_getattr_l__mod___layers___8_____0___layers_3 = None
    getattr_getattr_l__mod___layers___8_____0___layers_5 = self.getattr_getattr_L__mod___layers___8_____0___layers_5(getattr_getattr_l__mod___layers___8_____0___layers_4);  getattr_getattr_l__mod___layers___8_____0___layers_4 = None
    getattr_getattr_l__mod___layers___8_____0___layers_6 = self.getattr_getattr_L__mod___layers___8_____0___layers_6(getattr_getattr_l__mod___layers___8_____0___layers_5);  getattr_getattr_l__mod___layers___8_____0___layers_5 = None
    getattr_getattr_l__mod___layers___8_____0___layers_7 = self.getattr_getattr_L__mod___layers___8_____0___layers_7(getattr_getattr_l__mod___layers___8_____0___layers_6);  getattr_getattr_l__mod___layers___8_____0___layers_6 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:61, code: return self.layers(input) + input
    getattr_getattr_l__mod___layers___8_____1___layers_0 = self.getattr_getattr_L__mod___layers___8_____1___layers_0(getattr_getattr_l__mod___layers___8_____0___layers_7)
    getattr_getattr_l__mod___layers___8_____1___layers_1 = self.getattr_getattr_L__mod___layers___8_____1___layers_1(getattr_getattr_l__mod___layers___8_____1___layers_0);  getattr_getattr_l__mod___layers___8_____1___layers_0 = None
    getattr_getattr_l__mod___layers___8_____1___layers_2 = self.getattr_getattr_L__mod___layers___8_____1___layers_2(getattr_getattr_l__mod___layers___8_____1___layers_1);  getattr_getattr_l__mod___layers___8_____1___layers_1 = None
    getattr_getattr_l__mod___layers___8_____1___layers_3 = self.getattr_getattr_L__mod___layers___8_____1___layers_3(getattr_getattr_l__mod___layers___8_____1___layers_2);  getattr_getattr_l__mod___layers___8_____1___layers_2 = None
    getattr_getattr_l__mod___layers___8_____1___layers_4 = self.getattr_getattr_L__mod___layers___8_____1___layers_4(getattr_getattr_l__mod___layers___8_____1___layers_3);  getattr_getattr_l__mod___layers___8_____1___layers_3 = None
    getattr_getattr_l__mod___layers___8_____1___layers_5 = self.getattr_getattr_L__mod___layers___8_____1___layers_5(getattr_getattr_l__mod___layers___8_____1___layers_4);  getattr_getattr_l__mod___layers___8_____1___layers_4 = None
    getattr_getattr_l__mod___layers___8_____1___layers_6 = self.getattr_getattr_L__mod___layers___8_____1___layers_6(getattr_getattr_l__mod___layers___8_____1___layers_5);  getattr_getattr_l__mod___layers___8_____1___layers_5 = None
    getattr_getattr_l__mod___layers___8_____1___layers_7 = self.getattr_getattr_L__mod___layers___8_____1___layers_7(getattr_getattr_l__mod___layers___8_____1___layers_6);  getattr_getattr_l__mod___layers___8_____1___layers_6 = None
    add = getattr_getattr_l__mod___layers___8_____1___layers_7 + getattr_getattr_l__mod___layers___8_____0___layers_7;  getattr_getattr_l__mod___layers___8_____1___layers_7 = getattr_getattr_l__mod___layers___8_____0___layers_7 = None
    getattr_getattr_l__mod___layers___8_____2___layers_0 = self.getattr_getattr_L__mod___layers___8_____2___layers_0(add)
    getattr_getattr_l__mod___layers___8_____2___layers_1 = self.getattr_getattr_L__mod___layers___8_____2___layers_1(getattr_getattr_l__mod___layers___8_____2___layers_0);  getattr_getattr_l__mod___layers___8_____2___layers_0 = None
    getattr_getattr_l__mod___layers___8_____2___layers_2 = self.getattr_getattr_L__mod___layers___8_____2___layers_2(getattr_getattr_l__mod___layers___8_____2___layers_1);  getattr_getattr_l__mod___layers___8_____2___layers_1 = None
    getattr_getattr_l__mod___layers___8_____2___layers_3 = self.getattr_getattr_L__mod___layers___8_____2___layers_3(getattr_getattr_l__mod___layers___8_____2___layers_2);  getattr_getattr_l__mod___layers___8_____2___layers_2 = None
    getattr_getattr_l__mod___layers___8_____2___layers_4 = self.getattr_getattr_L__mod___layers___8_____2___layers_4(getattr_getattr_l__mod___layers___8_____2___layers_3);  getattr_getattr_l__mod___layers___8_____2___layers_3 = None
    getattr_getattr_l__mod___layers___8_____2___layers_5 = self.getattr_getattr_L__mod___layers___8_____2___layers_5(getattr_getattr_l__mod___layers___8_____2___layers_4);  getattr_getattr_l__mod___layers___8_____2___layers_4 = None
    getattr_getattr_l__mod___layers___8_____2___layers_6 = self.getattr_getattr_L__mod___layers___8_____2___layers_6(getattr_getattr_l__mod___layers___8_____2___layers_5);  getattr_getattr_l__mod___layers___8_____2___layers_5 = None
    getattr_getattr_l__mod___layers___8_____2___layers_7 = self.getattr_getattr_L__mod___layers___8_____2___layers_7(getattr_getattr_l__mod___layers___8_____2___layers_6);  getattr_getattr_l__mod___layers___8_____2___layers_6 = None
    add_1 = getattr_getattr_l__mod___layers___8_____2___layers_7 + add;  getattr_getattr_l__mod___layers___8_____2___layers_7 = add = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:63, code: return self.layers(input)
    getattr_getattr_l__mod___layers___9_____0___layers_0 = self.getattr_getattr_L__mod___layers___9_____0___layers_0(add_1);  add_1 = None
    getattr_getattr_l__mod___layers___9_____0___layers_1 = self.getattr_getattr_L__mod___layers___9_____0___layers_1(getattr_getattr_l__mod___layers___9_____0___layers_0);  getattr_getattr_l__mod___layers___9_____0___layers_0 = None
    getattr_getattr_l__mod___layers___9_____0___layers_2 = self.getattr_getattr_L__mod___layers___9_____0___layers_2(getattr_getattr_l__mod___layers___9_____0___layers_1);  getattr_getattr_l__mod___layers___9_____0___layers_1 = None
    getattr_getattr_l__mod___layers___9_____0___layers_3 = self.getattr_getattr_L__mod___layers___9_____0___layers_3(getattr_getattr_l__mod___layers___9_____0___layers_2);  getattr_getattr_l__mod___layers___9_____0___layers_2 = None
    getattr_getattr_l__mod___layers___9_____0___layers_4 = self.getattr_getattr_L__mod___layers___9_____0___layers_4(getattr_getattr_l__mod___layers___9_____0___layers_3);  getattr_getattr_l__mod___layers___9_____0___layers_3 = None
    getattr_getattr_l__mod___layers___9_____0___layers_5 = self.getattr_getattr_L__mod___layers___9_____0___layers_5(getattr_getattr_l__mod___layers___9_____0___layers_4);  getattr_getattr_l__mod___layers___9_____0___layers_4 = None
    getattr_getattr_l__mod___layers___9_____0___layers_6 = self.getattr_getattr_L__mod___layers___9_____0___layers_6(getattr_getattr_l__mod___layers___9_____0___layers_5);  getattr_getattr_l__mod___layers___9_____0___layers_5 = None
    getattr_getattr_l__mod___layers___9_____0___layers_7 = self.getattr_getattr_L__mod___layers___9_____0___layers_7(getattr_getattr_l__mod___layers___9_____0___layers_6);  getattr_getattr_l__mod___layers___9_____0___layers_6 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:61, code: return self.layers(input) + input
    getattr_getattr_l__mod___layers___9_____1___layers_0 = self.getattr_getattr_L__mod___layers___9_____1___layers_0(getattr_getattr_l__mod___layers___9_____0___layers_7)
    getattr_getattr_l__mod___layers___9_____1___layers_1 = self.getattr_getattr_L__mod___layers___9_____1___layers_1(getattr_getattr_l__mod___layers___9_____1___layers_0);  getattr_getattr_l__mod___layers___9_____1___layers_0 = None
    getattr_getattr_l__mod___layers___9_____1___layers_2 = self.getattr_getattr_L__mod___layers___9_____1___layers_2(getattr_getattr_l__mod___layers___9_____1___layers_1);  getattr_getattr_l__mod___layers___9_____1___layers_1 = None
    getattr_getattr_l__mod___layers___9_____1___layers_3 = self.getattr_getattr_L__mod___layers___9_____1___layers_3(getattr_getattr_l__mod___layers___9_____1___layers_2);  getattr_getattr_l__mod___layers___9_____1___layers_2 = None
    getattr_getattr_l__mod___layers___9_____1___layers_4 = self.getattr_getattr_L__mod___layers___9_____1___layers_4(getattr_getattr_l__mod___layers___9_____1___layers_3);  getattr_getattr_l__mod___layers___9_____1___layers_3 = None
    getattr_getattr_l__mod___layers___9_____1___layers_5 = self.getattr_getattr_L__mod___layers___9_____1___layers_5(getattr_getattr_l__mod___layers___9_____1___layers_4);  getattr_getattr_l__mod___layers___9_____1___layers_4 = None
    getattr_getattr_l__mod___layers___9_____1___layers_6 = self.getattr_getattr_L__mod___layers___9_____1___layers_6(getattr_getattr_l__mod___layers___9_____1___layers_5);  getattr_getattr_l__mod___layers___9_____1___layers_5 = None
    getattr_getattr_l__mod___layers___9_____1___layers_7 = self.getattr_getattr_L__mod___layers___9_____1___layers_7(getattr_getattr_l__mod___layers___9_____1___layers_6);  getattr_getattr_l__mod___layers___9_____1___layers_6 = None
    add_2 = getattr_getattr_l__mod___layers___9_____1___layers_7 + getattr_getattr_l__mod___layers___9_____0___layers_7;  getattr_getattr_l__mod___layers___9_____1___layers_7 = getattr_getattr_l__mod___layers___9_____0___layers_7 = None
    getattr_getattr_l__mod___layers___9_____2___layers_0 = self.getattr_getattr_L__mod___layers___9_____2___layers_0(add_2)
    getattr_getattr_l__mod___layers___9_____2___layers_1 = self.getattr_getattr_L__mod___layers___9_____2___layers_1(getattr_getattr_l__mod___layers___9_____2___layers_0);  getattr_getattr_l__mod___layers___9_____2___layers_0 = None
    getattr_getattr_l__mod___layers___9_____2___layers_2 = self.getattr_getattr_L__mod___layers___9_____2___layers_2(getattr_getattr_l__mod___layers___9_____2___layers_1);  getattr_getattr_l__mod___layers___9_____2___layers_1 = None
    getattr_getattr_l__mod___layers___9_____2___layers_3 = self.getattr_getattr_L__mod___layers___9_____2___layers_3(getattr_getattr_l__mod___layers___9_____2___layers_2);  getattr_getattr_l__mod___layers___9_____2___layers_2 = None
    getattr_getattr_l__mod___layers___9_____2___layers_4 = self.getattr_getattr_L__mod___layers___9_____2___layers_4(getattr_getattr_l__mod___layers___9_____2___layers_3);  getattr_getattr_l__mod___layers___9_____2___layers_3 = None
    getattr_getattr_l__mod___layers___9_____2___layers_5 = self.getattr_getattr_L__mod___layers___9_____2___layers_5(getattr_getattr_l__mod___layers___9_____2___layers_4);  getattr_getattr_l__mod___layers___9_____2___layers_4 = None
    getattr_getattr_l__mod___layers___9_____2___layers_6 = self.getattr_getattr_L__mod___layers___9_____2___layers_6(getattr_getattr_l__mod___layers___9_____2___layers_5);  getattr_getattr_l__mod___layers___9_____2___layers_5 = None
    getattr_getattr_l__mod___layers___9_____2___layers_7 = self.getattr_getattr_L__mod___layers___9_____2___layers_7(getattr_getattr_l__mod___layers___9_____2___layers_6);  getattr_getattr_l__mod___layers___9_____2___layers_6 = None
    add_3 = getattr_getattr_l__mod___layers___9_____2___layers_7 + add_2;  getattr_getattr_l__mod___layers___9_____2___layers_7 = add_2 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:63, code: return self.layers(input)
    getattr_getattr_l__mod___layers___10_____0___layers_0 = self.getattr_getattr_L__mod___layers___10_____0___layers_0(add_3);  add_3 = None
    getattr_getattr_l__mod___layers___10_____0___layers_1 = self.getattr_getattr_L__mod___layers___10_____0___layers_1(getattr_getattr_l__mod___layers___10_____0___layers_0);  getattr_getattr_l__mod___layers___10_____0___layers_0 = None
    getattr_getattr_l__mod___layers___10_____0___layers_2 = self.getattr_getattr_L__mod___layers___10_____0___layers_2(getattr_getattr_l__mod___layers___10_____0___layers_1);  getattr_getattr_l__mod___layers___10_____0___layers_1 = None
    getattr_getattr_l__mod___layers___10_____0___layers_3 = self.getattr_getattr_L__mod___layers___10_____0___layers_3(getattr_getattr_l__mod___layers___10_____0___layers_2);  getattr_getattr_l__mod___layers___10_____0___layers_2 = None
    getattr_getattr_l__mod___layers___10_____0___layers_4 = self.getattr_getattr_L__mod___layers___10_____0___layers_4(getattr_getattr_l__mod___layers___10_____0___layers_3);  getattr_getattr_l__mod___layers___10_____0___layers_3 = None
    getattr_getattr_l__mod___layers___10_____0___layers_5 = self.getattr_getattr_L__mod___layers___10_____0___layers_5(getattr_getattr_l__mod___layers___10_____0___layers_4);  getattr_getattr_l__mod___layers___10_____0___layers_4 = None
    getattr_getattr_l__mod___layers___10_____0___layers_6 = self.getattr_getattr_L__mod___layers___10_____0___layers_6(getattr_getattr_l__mod___layers___10_____0___layers_5);  getattr_getattr_l__mod___layers___10_____0___layers_5 = None
    getattr_getattr_l__mod___layers___10_____0___layers_7 = self.getattr_getattr_L__mod___layers___10_____0___layers_7(getattr_getattr_l__mod___layers___10_____0___layers_6);  getattr_getattr_l__mod___layers___10_____0___layers_6 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:61, code: return self.layers(input) + input
    getattr_getattr_l__mod___layers___10_____1___layers_0 = self.getattr_getattr_L__mod___layers___10_____1___layers_0(getattr_getattr_l__mod___layers___10_____0___layers_7)
    getattr_getattr_l__mod___layers___10_____1___layers_1 = self.getattr_getattr_L__mod___layers___10_____1___layers_1(getattr_getattr_l__mod___layers___10_____1___layers_0);  getattr_getattr_l__mod___layers___10_____1___layers_0 = None
    getattr_getattr_l__mod___layers___10_____1___layers_2 = self.getattr_getattr_L__mod___layers___10_____1___layers_2(getattr_getattr_l__mod___layers___10_____1___layers_1);  getattr_getattr_l__mod___layers___10_____1___layers_1 = None
    getattr_getattr_l__mod___layers___10_____1___layers_3 = self.getattr_getattr_L__mod___layers___10_____1___layers_3(getattr_getattr_l__mod___layers___10_____1___layers_2);  getattr_getattr_l__mod___layers___10_____1___layers_2 = None
    getattr_getattr_l__mod___layers___10_____1___layers_4 = self.getattr_getattr_L__mod___layers___10_____1___layers_4(getattr_getattr_l__mod___layers___10_____1___layers_3);  getattr_getattr_l__mod___layers___10_____1___layers_3 = None
    getattr_getattr_l__mod___layers___10_____1___layers_5 = self.getattr_getattr_L__mod___layers___10_____1___layers_5(getattr_getattr_l__mod___layers___10_____1___layers_4);  getattr_getattr_l__mod___layers___10_____1___layers_4 = None
    getattr_getattr_l__mod___layers___10_____1___layers_6 = self.getattr_getattr_L__mod___layers___10_____1___layers_6(getattr_getattr_l__mod___layers___10_____1___layers_5);  getattr_getattr_l__mod___layers___10_____1___layers_5 = None
    getattr_getattr_l__mod___layers___10_____1___layers_7 = self.getattr_getattr_L__mod___layers___10_____1___layers_7(getattr_getattr_l__mod___layers___10_____1___layers_6);  getattr_getattr_l__mod___layers___10_____1___layers_6 = None
    add_4 = getattr_getattr_l__mod___layers___10_____1___layers_7 + getattr_getattr_l__mod___layers___10_____0___layers_7;  getattr_getattr_l__mod___layers___10_____1___layers_7 = getattr_getattr_l__mod___layers___10_____0___layers_7 = None
    getattr_getattr_l__mod___layers___10_____2___layers_0 = self.getattr_getattr_L__mod___layers___10_____2___layers_0(add_4)
    getattr_getattr_l__mod___layers___10_____2___layers_1 = self.getattr_getattr_L__mod___layers___10_____2___layers_1(getattr_getattr_l__mod___layers___10_____2___layers_0);  getattr_getattr_l__mod___layers___10_____2___layers_0 = None
    getattr_getattr_l__mod___layers___10_____2___layers_2 = self.getattr_getattr_L__mod___layers___10_____2___layers_2(getattr_getattr_l__mod___layers___10_____2___layers_1);  getattr_getattr_l__mod___layers___10_____2___layers_1 = None
    getattr_getattr_l__mod___layers___10_____2___layers_3 = self.getattr_getattr_L__mod___layers___10_____2___layers_3(getattr_getattr_l__mod___layers___10_____2___layers_2);  getattr_getattr_l__mod___layers___10_____2___layers_2 = None
    getattr_getattr_l__mod___layers___10_____2___layers_4 = self.getattr_getattr_L__mod___layers___10_____2___layers_4(getattr_getattr_l__mod___layers___10_____2___layers_3);  getattr_getattr_l__mod___layers___10_____2___layers_3 = None
    getattr_getattr_l__mod___layers___10_____2___layers_5 = self.getattr_getattr_L__mod___layers___10_____2___layers_5(getattr_getattr_l__mod___layers___10_____2___layers_4);  getattr_getattr_l__mod___layers___10_____2___layers_4 = None
    getattr_getattr_l__mod___layers___10_____2___layers_6 = self.getattr_getattr_L__mod___layers___10_____2___layers_6(getattr_getattr_l__mod___layers___10_____2___layers_5);  getattr_getattr_l__mod___layers___10_____2___layers_5 = None
    getattr_getattr_l__mod___layers___10_____2___layers_7 = self.getattr_getattr_L__mod___layers___10_____2___layers_7(getattr_getattr_l__mod___layers___10_____2___layers_6);  getattr_getattr_l__mod___layers___10_____2___layers_6 = None
    add_5 = getattr_getattr_l__mod___layers___10_____2___layers_7 + add_4;  getattr_getattr_l__mod___layers___10_____2___layers_7 = add_4 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:63, code: return self.layers(input)
    getattr_getattr_l__mod___layers___11_____0___layers_0 = self.getattr_getattr_L__mod___layers___11_____0___layers_0(add_5);  add_5 = None
    getattr_getattr_l__mod___layers___11_____0___layers_1 = self.getattr_getattr_L__mod___layers___11_____0___layers_1(getattr_getattr_l__mod___layers___11_____0___layers_0);  getattr_getattr_l__mod___layers___11_____0___layers_0 = None
    getattr_getattr_l__mod___layers___11_____0___layers_2 = self.getattr_getattr_L__mod___layers___11_____0___layers_2(getattr_getattr_l__mod___layers___11_____0___layers_1);  getattr_getattr_l__mod___layers___11_____0___layers_1 = None
    getattr_getattr_l__mod___layers___11_____0___layers_3 = self.getattr_getattr_L__mod___layers___11_____0___layers_3(getattr_getattr_l__mod___layers___11_____0___layers_2);  getattr_getattr_l__mod___layers___11_____0___layers_2 = None
    getattr_getattr_l__mod___layers___11_____0___layers_4 = self.getattr_getattr_L__mod___layers___11_____0___layers_4(getattr_getattr_l__mod___layers___11_____0___layers_3);  getattr_getattr_l__mod___layers___11_____0___layers_3 = None
    getattr_getattr_l__mod___layers___11_____0___layers_5 = self.getattr_getattr_L__mod___layers___11_____0___layers_5(getattr_getattr_l__mod___layers___11_____0___layers_4);  getattr_getattr_l__mod___layers___11_____0___layers_4 = None
    getattr_getattr_l__mod___layers___11_____0___layers_6 = self.getattr_getattr_L__mod___layers___11_____0___layers_6(getattr_getattr_l__mod___layers___11_____0___layers_5);  getattr_getattr_l__mod___layers___11_____0___layers_5 = None
    getattr_getattr_l__mod___layers___11_____0___layers_7 = self.getattr_getattr_L__mod___layers___11_____0___layers_7(getattr_getattr_l__mod___layers___11_____0___layers_6);  getattr_getattr_l__mod___layers___11_____0___layers_6 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:61, code: return self.layers(input) + input
    getattr_getattr_l__mod___layers___11_____1___layers_0 = self.getattr_getattr_L__mod___layers___11_____1___layers_0(getattr_getattr_l__mod___layers___11_____0___layers_7)
    getattr_getattr_l__mod___layers___11_____1___layers_1 = self.getattr_getattr_L__mod___layers___11_____1___layers_1(getattr_getattr_l__mod___layers___11_____1___layers_0);  getattr_getattr_l__mod___layers___11_____1___layers_0 = None
    getattr_getattr_l__mod___layers___11_____1___layers_2 = self.getattr_getattr_L__mod___layers___11_____1___layers_2(getattr_getattr_l__mod___layers___11_____1___layers_1);  getattr_getattr_l__mod___layers___11_____1___layers_1 = None
    getattr_getattr_l__mod___layers___11_____1___layers_3 = self.getattr_getattr_L__mod___layers___11_____1___layers_3(getattr_getattr_l__mod___layers___11_____1___layers_2);  getattr_getattr_l__mod___layers___11_____1___layers_2 = None
    getattr_getattr_l__mod___layers___11_____1___layers_4 = self.getattr_getattr_L__mod___layers___11_____1___layers_4(getattr_getattr_l__mod___layers___11_____1___layers_3);  getattr_getattr_l__mod___layers___11_____1___layers_3 = None
    getattr_getattr_l__mod___layers___11_____1___layers_5 = self.getattr_getattr_L__mod___layers___11_____1___layers_5(getattr_getattr_l__mod___layers___11_____1___layers_4);  getattr_getattr_l__mod___layers___11_____1___layers_4 = None
    getattr_getattr_l__mod___layers___11_____1___layers_6 = self.getattr_getattr_L__mod___layers___11_____1___layers_6(getattr_getattr_l__mod___layers___11_____1___layers_5);  getattr_getattr_l__mod___layers___11_____1___layers_5 = None
    getattr_getattr_l__mod___layers___11_____1___layers_7 = self.getattr_getattr_L__mod___layers___11_____1___layers_7(getattr_getattr_l__mod___layers___11_____1___layers_6);  getattr_getattr_l__mod___layers___11_____1___layers_6 = None
    add_6 = getattr_getattr_l__mod___layers___11_____1___layers_7 + getattr_getattr_l__mod___layers___11_____0___layers_7;  getattr_getattr_l__mod___layers___11_____1___layers_7 = getattr_getattr_l__mod___layers___11_____0___layers_7 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:63, code: return self.layers(input)
    getattr_getattr_l__mod___layers___12_____0___layers_0 = self.getattr_getattr_L__mod___layers___12_____0___layers_0(add_6);  add_6 = None
    getattr_getattr_l__mod___layers___12_____0___layers_1 = self.getattr_getattr_L__mod___layers___12_____0___layers_1(getattr_getattr_l__mod___layers___12_____0___layers_0);  getattr_getattr_l__mod___layers___12_____0___layers_0 = None
    getattr_getattr_l__mod___layers___12_____0___layers_2 = self.getattr_getattr_L__mod___layers___12_____0___layers_2(getattr_getattr_l__mod___layers___12_____0___layers_1);  getattr_getattr_l__mod___layers___12_____0___layers_1 = None
    getattr_getattr_l__mod___layers___12_____0___layers_3 = self.getattr_getattr_L__mod___layers___12_____0___layers_3(getattr_getattr_l__mod___layers___12_____0___layers_2);  getattr_getattr_l__mod___layers___12_____0___layers_2 = None
    getattr_getattr_l__mod___layers___12_____0___layers_4 = self.getattr_getattr_L__mod___layers___12_____0___layers_4(getattr_getattr_l__mod___layers___12_____0___layers_3);  getattr_getattr_l__mod___layers___12_____0___layers_3 = None
    getattr_getattr_l__mod___layers___12_____0___layers_5 = self.getattr_getattr_L__mod___layers___12_____0___layers_5(getattr_getattr_l__mod___layers___12_____0___layers_4);  getattr_getattr_l__mod___layers___12_____0___layers_4 = None
    getattr_getattr_l__mod___layers___12_____0___layers_6 = self.getattr_getattr_L__mod___layers___12_____0___layers_6(getattr_getattr_l__mod___layers___12_____0___layers_5);  getattr_getattr_l__mod___layers___12_____0___layers_5 = None
    getattr_getattr_l__mod___layers___12_____0___layers_7 = self.getattr_getattr_L__mod___layers___12_____0___layers_7(getattr_getattr_l__mod___layers___12_____0___layers_6);  getattr_getattr_l__mod___layers___12_____0___layers_6 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:61, code: return self.layers(input) + input
    getattr_getattr_l__mod___layers___12_____1___layers_0 = self.getattr_getattr_L__mod___layers___12_____1___layers_0(getattr_getattr_l__mod___layers___12_____0___layers_7)
    getattr_getattr_l__mod___layers___12_____1___layers_1 = self.getattr_getattr_L__mod___layers___12_____1___layers_1(getattr_getattr_l__mod___layers___12_____1___layers_0);  getattr_getattr_l__mod___layers___12_____1___layers_0 = None
    getattr_getattr_l__mod___layers___12_____1___layers_2 = self.getattr_getattr_L__mod___layers___12_____1___layers_2(getattr_getattr_l__mod___layers___12_____1___layers_1);  getattr_getattr_l__mod___layers___12_____1___layers_1 = None
    getattr_getattr_l__mod___layers___12_____1___layers_3 = self.getattr_getattr_L__mod___layers___12_____1___layers_3(getattr_getattr_l__mod___layers___12_____1___layers_2);  getattr_getattr_l__mod___layers___12_____1___layers_2 = None
    getattr_getattr_l__mod___layers___12_____1___layers_4 = self.getattr_getattr_L__mod___layers___12_____1___layers_4(getattr_getattr_l__mod___layers___12_____1___layers_3);  getattr_getattr_l__mod___layers___12_____1___layers_3 = None
    getattr_getattr_l__mod___layers___12_____1___layers_5 = self.getattr_getattr_L__mod___layers___12_____1___layers_5(getattr_getattr_l__mod___layers___12_____1___layers_4);  getattr_getattr_l__mod___layers___12_____1___layers_4 = None
    getattr_getattr_l__mod___layers___12_____1___layers_6 = self.getattr_getattr_L__mod___layers___12_____1___layers_6(getattr_getattr_l__mod___layers___12_____1___layers_5);  getattr_getattr_l__mod___layers___12_____1___layers_5 = None
    getattr_getattr_l__mod___layers___12_____1___layers_7 = self.getattr_getattr_L__mod___layers___12_____1___layers_7(getattr_getattr_l__mod___layers___12_____1___layers_6);  getattr_getattr_l__mod___layers___12_____1___layers_6 = None
    add_7 = getattr_getattr_l__mod___layers___12_____1___layers_7 + getattr_getattr_l__mod___layers___12_____0___layers_7;  getattr_getattr_l__mod___layers___12_____1___layers_7 = getattr_getattr_l__mod___layers___12_____0___layers_7 = None
    getattr_getattr_l__mod___layers___12_____2___layers_0 = self.getattr_getattr_L__mod___layers___12_____2___layers_0(add_7)
    getattr_getattr_l__mod___layers___12_____2___layers_1 = self.getattr_getattr_L__mod___layers___12_____2___layers_1(getattr_getattr_l__mod___layers___12_____2___layers_0);  getattr_getattr_l__mod___layers___12_____2___layers_0 = None
    getattr_getattr_l__mod___layers___12_____2___layers_2 = self.getattr_getattr_L__mod___layers___12_____2___layers_2(getattr_getattr_l__mod___layers___12_____2___layers_1);  getattr_getattr_l__mod___layers___12_____2___layers_1 = None
    getattr_getattr_l__mod___layers___12_____2___layers_3 = self.getattr_getattr_L__mod___layers___12_____2___layers_3(getattr_getattr_l__mod___layers___12_____2___layers_2);  getattr_getattr_l__mod___layers___12_____2___layers_2 = None
    getattr_getattr_l__mod___layers___12_____2___layers_4 = self.getattr_getattr_L__mod___layers___12_____2___layers_4(getattr_getattr_l__mod___layers___12_____2___layers_3);  getattr_getattr_l__mod___layers___12_____2___layers_3 = None
    getattr_getattr_l__mod___layers___12_____2___layers_5 = self.getattr_getattr_L__mod___layers___12_____2___layers_5(getattr_getattr_l__mod___layers___12_____2___layers_4);  getattr_getattr_l__mod___layers___12_____2___layers_4 = None
    getattr_getattr_l__mod___layers___12_____2___layers_6 = self.getattr_getattr_L__mod___layers___12_____2___layers_6(getattr_getattr_l__mod___layers___12_____2___layers_5);  getattr_getattr_l__mod___layers___12_____2___layers_5 = None
    getattr_getattr_l__mod___layers___12_____2___layers_7 = self.getattr_getattr_L__mod___layers___12_____2___layers_7(getattr_getattr_l__mod___layers___12_____2___layers_6);  getattr_getattr_l__mod___layers___12_____2___layers_6 = None
    add_8 = getattr_getattr_l__mod___layers___12_____2___layers_7 + add_7;  getattr_getattr_l__mod___layers___12_____2___layers_7 = add_7 = None
    getattr_getattr_l__mod___layers___12_____3___layers_0 = self.getattr_getattr_L__mod___layers___12_____3___layers_0(add_8)
    getattr_getattr_l__mod___layers___12_____3___layers_1 = self.getattr_getattr_L__mod___layers___12_____3___layers_1(getattr_getattr_l__mod___layers___12_____3___layers_0);  getattr_getattr_l__mod___layers___12_____3___layers_0 = None
    getattr_getattr_l__mod___layers___12_____3___layers_2 = self.getattr_getattr_L__mod___layers___12_____3___layers_2(getattr_getattr_l__mod___layers___12_____3___layers_1);  getattr_getattr_l__mod___layers___12_____3___layers_1 = None
    getattr_getattr_l__mod___layers___12_____3___layers_3 = self.getattr_getattr_L__mod___layers___12_____3___layers_3(getattr_getattr_l__mod___layers___12_____3___layers_2);  getattr_getattr_l__mod___layers___12_____3___layers_2 = None
    getattr_getattr_l__mod___layers___12_____3___layers_4 = self.getattr_getattr_L__mod___layers___12_____3___layers_4(getattr_getattr_l__mod___layers___12_____3___layers_3);  getattr_getattr_l__mod___layers___12_____3___layers_3 = None
    getattr_getattr_l__mod___layers___12_____3___layers_5 = self.getattr_getattr_L__mod___layers___12_____3___layers_5(getattr_getattr_l__mod___layers___12_____3___layers_4);  getattr_getattr_l__mod___layers___12_____3___layers_4 = None
    getattr_getattr_l__mod___layers___12_____3___layers_6 = self.getattr_getattr_L__mod___layers___12_____3___layers_6(getattr_getattr_l__mod___layers___12_____3___layers_5);  getattr_getattr_l__mod___layers___12_____3___layers_5 = None
    getattr_getattr_l__mod___layers___12_____3___layers_7 = self.getattr_getattr_L__mod___layers___12_____3___layers_7(getattr_getattr_l__mod___layers___12_____3___layers_6);  getattr_getattr_l__mod___layers___12_____3___layers_6 = None
    add_9 = getattr_getattr_l__mod___layers___12_____3___layers_7 + add_8;  getattr_getattr_l__mod___layers___12_____3___layers_7 = add_8 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:63, code: return self.layers(input)
    getattr_getattr_l__mod___layers___13_____0___layers_0 = self.getattr_getattr_L__mod___layers___13_____0___layers_0(add_9);  add_9 = None
    getattr_getattr_l__mod___layers___13_____0___layers_1 = self.getattr_getattr_L__mod___layers___13_____0___layers_1(getattr_getattr_l__mod___layers___13_____0___layers_0);  getattr_getattr_l__mod___layers___13_____0___layers_0 = None
    getattr_getattr_l__mod___layers___13_____0___layers_2 = self.getattr_getattr_L__mod___layers___13_____0___layers_2(getattr_getattr_l__mod___layers___13_____0___layers_1);  getattr_getattr_l__mod___layers___13_____0___layers_1 = None
    getattr_getattr_l__mod___layers___13_____0___layers_3 = self.getattr_getattr_L__mod___layers___13_____0___layers_3(getattr_getattr_l__mod___layers___13_____0___layers_2);  getattr_getattr_l__mod___layers___13_____0___layers_2 = None
    getattr_getattr_l__mod___layers___13_____0___layers_4 = self.getattr_getattr_L__mod___layers___13_____0___layers_4(getattr_getattr_l__mod___layers___13_____0___layers_3);  getattr_getattr_l__mod___layers___13_____0___layers_3 = None
    getattr_getattr_l__mod___layers___13_____0___layers_5 = self.getattr_getattr_L__mod___layers___13_____0___layers_5(getattr_getattr_l__mod___layers___13_____0___layers_4);  getattr_getattr_l__mod___layers___13_____0___layers_4 = None
    getattr_getattr_l__mod___layers___13_____0___layers_6 = self.getattr_getattr_L__mod___layers___13_____0___layers_6(getattr_getattr_l__mod___layers___13_____0___layers_5);  getattr_getattr_l__mod___layers___13_____0___layers_5 = None
    getattr_getattr_l__mod___layers___13_____0___layers_7 = self.getattr_getattr_L__mod___layers___13_____0___layers_7(getattr_getattr_l__mod___layers___13_____0___layers_6);  getattr_getattr_l__mod___layers___13_____0___layers_6 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:159, code: x = self.layers(x)
    l__mod___layers_14 = self.L__mod___layers_14(getattr_getattr_l__mod___layers___13_____0___layers_7);  getattr_getattr_l__mod___layers___13_____0___layers_7 = None
    l__mod___layers_15 = self.L__mod___layers_15(l__mod___layers_14);  l__mod___layers_14 = None
    x = self.L__mod___layers_16(l__mod___layers_15);  l__mod___layers_15 = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:161, code: x = x.mean([2, 3])
    x_1 = x.mean([2, 3]);  x = None
    
    # File: /workspace/youkaichao/code/torchvision/torchvision/models/mnasnet.py:162, code: return self.classifier(x)
    l__mod___classifier_0 = self.L__mod___classifier_0(x_1);  x_1 = None
    l__mod___classifier_1 = self.L__mod___classifier_1(l__mod___classifier_0);  l__mod___classifier_0 = None
    return (l__mod___classifier_1,)
    